package: structure_plus
version: 0.1.dev
author: Wolfgang Bund
supportpage: www.redaxo.org/de/forum/

page:
    title: Structure Plus
    pjax: true
    icon: rex-icon rex-icon-system
    perm: admin
    subpages:
        settings:
            title: Einstellungen
